export var Template = {
    skeleton: "\n        <div class=\"roolith__editor\" id=\"{editorId}\">\n            <div class=\"roolith__editor__toolbar\">\n                <ul class=\"roolith__editor__toolbar__list\"></ul>\n            </div>\n            <div class=\"roolith__editor__content\" contenteditable=\"true\" spellcheck=\"true\"></div>\n        </div>\n    ",
    button: "<li class=\"roolith__editor__toolbar__list__item\" data-command=\"{button}\"><button>{icon}</button></li>",
    separator: "<li class=\"roolith__editor__toolbar__list__item roolith__editor__toolbar__list__item--separator\">-</li>",
    headings: "\n        <li class=\"roolith__editor__toolbar__list__item roolith__editor__toolbar__list__item--dropdown\">\n            <div class=\"roolith__editor__toolbar__list__item__dropdown\">\n                <div class=\"roolith__editor__toolbar__list__item__dropdown__header\">Heading</div>\n                <ul class=\"roolith__editor__toolbar__list__item__dropdown__list\">\n                    <li class=\"roolith__editor__toolbar__list__item__dropdown__list__item is--h1\" data-command=\"formatBlock:h1\"><button>Heading 1</button></li>\n                    <li class=\"roolith__editor__toolbar__list__item__dropdown__list__item is--h2\" data-command=\"formatBlock:h2\"><button>Heading 2</button></li>\n                    <li class=\"roolith__editor__toolbar__list__item__dropdown__list__item is--h3\" data-command=\"formatBlock:h3\"><button>Heading 3</button></li>\n                    <li class=\"roolith__editor__toolbar__list__item__dropdown__list__item is--h4\" data-command=\"formatBlock:h4\"><button>Heading 4</button></li>\n                    <li class=\"roolith__editor__toolbar__list__item__dropdown__list__item is--h5\" data-command=\"formatBlock:h5\"><button>Heading 5</button></li>\n                    <li class=\"roolith__editor__toolbar__list__item__dropdown__list__item is--h6\" data-command=\"formatBlock:h6\"><button>Heading 6</button></li>\n                </ul>\n            </div>\n        </li>\n    ",
    modal: "\n        <div class=\"roolith__editor__modal\">\n            <div class=\"roolith__editor__modal__content\">\n                <div class=\"roolith__editor__modal__content__header\">{title} <button class=\"roolith__editor__modal__close\"></button></div>\n                <div class=\"roolith__editor__modal__content__body\">\n                    {content}\n                </div>\n                <div class=\"roolith__editor__modal__content__footer\">\n                    <button class=\"roolith__editor__modal__cta\">Insert</button>\n                </div>\n            </div>\n        </div>\n    ",
    image: "\n        <form class=\"roolith__editor__modal__form\" data-command=\"image\">\n            <div class=\"roolith__editor__modal__form__item\">\n                <label for=\"roolithModalImageTitle\" class=\"roolith__editor__modal__form__item__label\">Title</label>\n                <input type=\"text\" id=\"roolithModalImageTitle\" name=\"roolithModalImageTitle\" class=\"roolith__editor__modal__form__item__field\">\n            </div>\n            <div class=\"roolith__editor__modal__form__item\">\n                <label for=\"roolithModalImageUrl\" class=\"roolith__editor__modal__form__item__label\">URL</label>\n                <input type=\"text\" id=\"roolithModalImageUrl\" name=\"roolithModalImageUrl\" class=\"roolith__editor__modal__form__item__field\">\n            </div>\n        </form>\n    ",
    video: "\n        <form class=\"roolith__editor__modal__form\" data-command=\"video\">\n            <div class=\"roolith__editor__modal__form__item\">\n                <textarea type=\"text\" rows=\"5\" id=\"roolithModalEmbededCode\" name=\"roolithModalEmbededCode\" class=\"roolith__editor__modal__form__item__field\"></textarea>\n            </div>\n        </form>\n    "
};
